### ISSUE TITLE
Запрос на документацию для тестирования

### ISSUE THREAD

**Issue by alexmalder** [neg-serg/negwm#2]
Мне, как потенциальному тестировщику необходима следующая информация:
- [x] какие изменения повлечёт установка
- [x] как эти изменения при завершении тестов подчистить
- [x] принцип работы генератора на верхнем уровне
- [x] как работают модули
- [x] как это работает на уровне сокетов

**Comment by neg-serg** [comment]
>какие изменения повлечёт установка

В данный момент никакие особые зависимости в плане программ не устанавливаются. Раньше было сделано так, что предполагалось что скрипт сам это всё потянет, сейчас я подумал что лучше сделать это через условный PKGBUILD который может появиться в будущем. Опциональные зависимости в плане программ следующие, их можно будет установить отдельно:

```
'libxrandr: xrandr support'
'rofi: x11 menu'
'picom: X11 compositing support'
'zsh: better shell'
'tmux: terminal multiplexor'
'dunst: x11 notification daemon'
'xdo: x11 window manipulation tools'
'alacritty: terminal emulator'
'kitty: terminal emulator'
'pulseaudio: general-purpose sound server'
```

>как эти изменения при завершении тестов подчистить

В данный момент все яйца сложены в одну штанину, так что достаточно просто сделать `rm -rf ~/.config/negwm` или какой там задан `XDG_CONFIG_DIR`. В принципе всё возможности для того чтобы разнести это дело по разным директориям есть, просто пока не реализовано.

>принцип работы генератора на верхнем уровне

Эта штука была придумана для того чтобы изменения в конфиге, которые относятся к модулям, можно было писать в них самих. Также есть генерилка для конфига самого i3. Изначально великий план был написать её на hy(https://docs.hylang.org/en/stable/) но получилось то что получилось, может потом переделаю. Такой формат конфига в виде питоновской прогаммы выбран потому что для питона кмк это наиболее оптимальный способ сериализации. В целом его работа будет пересмотрена в будущем.

Как его следует читать: в `cfg/conf_gen.py` есть набор полей где что-то равно чему-то. Каждому такому равенству может соотв. функция, которая на основе шаблона генерит конфиг.

В будущем скорее всего придет к конфигам, которые основаны на функциях, без объектов, но это пока не сделано.

>как работают модули

Любые функции модулей можно вызывать либо `send_msg` внутри самого `negwm`, либо отправлять сообщения на порт 15555 в таком формате, например как:
`<имя модуля> <команда> <параметры через пробел>`, например:
`circle next term`.

С точки зрения вызова это может выглядеть например так:
`"echo 'circle next term' | /usr/bin/nc localhost 15555 -w 0"`

>как это работает на уровне сокетов

Как я уже сказал есть два варианта вызова функций. Используется обычный async event loop, который вычитывает строки по одной, сплитит их с помощью `.split()` и потом отсылает "сообщение" туда куда следует.

**Comment by alexmalder** [comment]
А можно какое-то описание самих модулей? В ответе есть информация о том, как пользоваться сразу всеми модулями обобщённо, и нет информации о том, что сами модули в себе скрывают. Будет вполне достаточно типового использования по каждому из них, думаю, что это немного.

**Comment by alexmalder** [comment]
Модули нашёл в README, осталось перевести на русский язык.
