### ISSUE TITLE
Логгирование negwm

### ISSUE THREAD

**Issue by alexmalder** [neg-serg/negwm#5]
В процессе использования negwm начали появляться разные идеи, некоторые из которых требуют записи лога в файл для отладки.
Прошу завести логгирование, например, в /var/log/negwm.log по умолчанию.

**Comment by neg-serg** [comment]
Естественно ни в какой `/var/log` это сделать нельзя и не планируется, потому что не ожидается что оно будет запускаться от рута. Можно просто улучшить уже существующее логирование через `journalctl --user`.

**Comment by alexmalder** [comment]
`journalctl -xeu negwm -f --user` логи показывает. 
Сервис работает через `systemd` при условии указания `systemctl --user import-environment I3SOCK` где-то в автозагрузке. Прошу занести в README эту информацию.
