### ISSUE TITLE
Опциональная горячая генерация конфига

### ISSUE THREAD

**Issue by alexmalder** [neg-serg/negwm#6]
Прошу сделать автогенерацию конфига i3/config опциональной в зависимости от аргументов запуска или переменной окружения.

**Comment by neg-serg** [comment]
В данном случае это написано так что триггером служит именно изменение в файле. Честно говоря я не вижу особого смысла менять логику специально под этот случай.

Вместо этого будет лучше вынести `conf_gen` в отдельную программу с отдельным репозиторием, благо сейчас для этого есть возможности.

**Comment by alexmalder** [comment]
Сейчас в отдельном репозитории хранится `conf_gen.cfg`, собственно, как и все остальные конфиги.
Сама мотивация этого запроса заключалась в том, что в некоторых случаях (например, невалидная конфигурация i3) встречалось неочевидное поведение, и когда-то конфиг генерился и применялся, а когда то нет.
Решено через обязательное применение конфига для получение обратной связи в случае невалидности от самого `i3`.
Таким образом ситуаций, где наблюдалось неочевидное поведение на текущий момент не наблюдается.
Спасибо.
