### ISSUE TITLE
Создать класс mode

### ISSUE THREAD

**Issue by alexmalder** [neg-serg/negwm#7]
Прошу завести класс mode вида `class mode(Enum)` по аналогии с другими классами, например, circle или scratchpad.

**Comment by neg-serg** [comment]
Это не будет сделано, т.к. как я уже сказал эта часть с конфигурилкой изменится когда до неё дойдут руки и примет вообще другой вид с отдельным репозиторием.

**Comment by alexmalder** [comment]
Понял, ожидаем обновлений.
